### ISSUE TITLE
rake setupfile で Errno::ENOENT

### ISSUE THREAD

**Issue by znz** [dogatana/rubima-kindle#2]
Linux 上で試してみると `rake setupfile` で `Errno::ENOENT` になってうまくいきませんでした。

```
% rake setupfile
mkdir -p kindle
cd download
ruby -I.. ../setupfile.rb kindle
# collecting file information
# processing p=0014-hotlinks_f=kakutani300x225.jpg
/home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:1281:in `initialize': No such file or directory @ rb_sysopen - p=0014-hotlinks_f=kakutani300x225.jpg (Errno::ENOENT)
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:1281:in `open'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:1281:in `copy_file'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:423:in `copy_file'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:350:in `block in cp'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:1453:in `block in fu_each_src_dest'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:1469:in `fu_each_src_dest0'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:1451:in `fu_each_src_dest'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/fileutils.rb:349:in `cp'
        from ../setupfile.rb:48:in `block in <main>'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/forwardable.rb:232:in `each'
        from /home/vagrant/.anyenv/envs/rbenv/versions/git/lib/ruby/2.4.0/forwardable.rb:232:in `each'
        from ../setupfile.rb:40:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I.. ../setupfile.rb kindle...]
/home/vagrant/s/github.com/dogatana/rubima-kindle/Rakefile:18:in `block (2 levels) in <top (required)>'
/home/vagrant/s/github.com/dogatana/rubima-kindle/Rakefile:17:in `block in <top (required)>'
Tasks: TOP => setupfile
(See full trace by running task with --trace)
```

**Comment by dogatana** [comment]
報告ありがとうございます。
setupfile.rb の処理がファイル名の大文字・小文字の差異でエラーが出る処理になっていました。
Windowsでは大文字・小文字の違いを無視するので問題が出ませんが、Linuxでは問題となります。
先程修正したので試していただければと思います。

**Comment by znz** [comment]
ちゃんと `kindle/rubima.mobi` が生成されて Kindle for Mac で開けることを確認しました。
ありがとうございます。

**Comment by dogatana** [comment]
良かったです。
Linux に Kindle Reader あったかしらん? と思っていたのですが、読むのはMacなんですね。
